<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**A Neuron can be defined as a function that receives at least one weighted input and sums them to make an activated output. Additionally they receive inputs and pass on their signal to the next layer of the neural network. The Neuron consits of the an input layer, hidden layer and an output layer. The Neuron bascially consist of numbers between 0 to 1.

- **Input Layer:** The input layer is the first layer of the neural network. It will receive at least one input, and sometimes many. Number of inputs nodes is basically correlated with the difficulty or complexity of the task at hand. After receiving the inputs, this layer will update the weights and send information to the hidden layer. This layer could also be referred to as the visible layer.

- **Hidden Layer:** They're used in neural network and can be picked based on experience. We really do not see their values and that's why they're referred to as hidden(invisible). They're also referred to as the blackbox. They're either connected to another hidden layer or the output layer

- **Output Layer:** The job of the output layer is to produce an output. This is what is been predicted. There would be 1 node when it is a binary classification or a simple regression. While in a multi class regression problem, there will be many nodes as possible outputs

- **Activation:** This can be referred to as a transfer function. Each node in a neural network has one and they're usually the same within each layer of the network. It determines whether a node sends information on to connected nodes in deeper layers.


- **Backpropagation:** This is the means by which neural network improves, it tells the ANN whether its prediction was correct or incorrect, and the network adjusts its parameters accordingly. Typically, it is done by computing the negative gradient of the error and then going through the network backwards to adjust the weights


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

In [7]:
candy['ate'].value_counts()

1    5000
0    5000
Name: ate, dtype: int64

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [4]:
# Start your candy perceptron here
import numpy as np

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

In [10]:
X.shape

(10000, 2)

In [40]:
X = np.array(candy[['chocolate', 'gummy']].values)
y = np.array(candy['ate'].values)

#reshape y
y = y.reshape(10000, 1)

In [41]:
#setting sigmoid functions

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [43]:
# randomize weights for inputs:
weights = 2 * np.random.random((2,1))

In [44]:
# weighted sums of inputs and weights
weighted_sum = np.dot(X, weights) 

In [45]:
activated_output = sigmoid(weighted_sum)

In [46]:
error = y - activated_output
error

array([[0.14659348],
       [0.38383169],
       [0.14659348],
       ...,
       [0.14659348],
       [0.14659348],
       [0.38383169]])

In [47]:
adjustments = error * sigmoid_derivative(activated_output)
adjustments

array([[0.03070926],
       [0.08739678],
       [0.03070926],
       ...,
       [0.03070926],
       [0.03070926],
       [0.08739678]])

In [48]:
weights += np.dot(X.T, adjustments)
weights

array([[-246.67454186],
       [-384.26233216]])

In [51]:
# set iterations
iters = 1000
# set learning rate
learning_rate = .01
# set initial weights
weights = 2 * np.random.random((2,1)) - 1
# updates weights for the ammount of times in iters
for _ in range(iters):
    # gets weighted sums
    weighted_sum = np.dot(X, weights)
    # activates weighted sums
    activated_output = sigmoid(weighted_sum)
    # gets error
    error = y - activated_output
    # finds adjustment value and applies learning rate
    adjustments = learning_rate * error * sigmoid_derivative(activated_output)
    # updates weights
    weights += np.dot(X.T, adjustments)
# returns most recent activation values        
print("Weight after training")
print(weights)

print("Output after training")
print(activated_output)

Weight after training
[[-1.46096637]
 [-1.46154105]]
Output after training
[[0.96286178]
 [0.96280629]
 [0.96286178]
 ...
 [0.96286178]
 [0.96286178]
 [0.96280629]]


In [42]:
def binary_predict(x):
    predictions = []
    for i in x:
        if i < .5:
            predictions.append([0])
        else:
            predictions.append([1])
    return(predictions)
            

In [50]:
y_pred = binary_predict(activated_output)
cor_predictions = np.sum(y_pred == y)
total_predictions = len(y)
accuracy = cor_predictions / total_predictions
print(f'Accuracy score: {accuracy}')


Accuracy score: 0.5


In [ ]:
The accuracy for the perceptron is low . This perceptron can not separate these outcomes effectively thus the poor accuracy. If the candy is chocolate or gummy, a child is likely to eat it but if its both or neither, then the child is not likely to eat it

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [52]:
class NeuralNetwork:
    def __init__(self, inputs, hiddenNodes, outputNodes=1):
        self.inputs = inputs
        self.hiddenNodes =  hiddenNodes
        self.outputNodes = outputNodes
        self.inputWeights = np.random.randn(self.inputs, self.hiddenNodes)
        self.hiddenWeights = np.random.randn(self.hiddenNodes, self.outputNodes)
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    def sigmoidPrime(self, s):
        return s * (1-s)
    def feed_forward(self, X):
        self.hiddenSum = np.dot(X, self.inputWeights)
        self.hiddenActv = self.sigmoid(self.hiddenSum)
        self.outputSum = np.dot(self.hiddenActv, self.hiddenWeights)
        self.outputActv = self.sigmoid(self.outputSum)
        return(self.outputActv) # used as output for backward
    def backward(self, X, y, output, learning_rate=.1):
        self.outputError = y - output
        self.outputDelta = learning_rate * (self.outputError * self.sigmoidPrime(output)) 
        self.hiddenError = self.outputDelta.dot(self.hiddenWeights.T)
        self.hiddenDelta = self.hiddenError * self.sigmoidPrime(self.hiddenActv)
        self.hiddenWeights += self.hiddenActv.T.dot(self.outputDelta)
        self.inputWeights += X.T.dot(self.hiddenDelta)
    def train(self, X, y, epochs=100, learning_rate=.1):
        for _ in range(epochs):
            output = self.feed_forward(X)
            self.backward(X, y, output, learning_rate=learning_rate)
        self.loss = np.mean(np.square(y - self.feed_forward(X)))
        print(f'\nLoss after {epochs} epochs was {self.loss}\n')
    def predict(self, X):
        output = self.feed_forward(X)
        predictions = []
        for i in output:
            if i[0] >= 0.5:
                predictions.append([1])
            else:
                predictions.append([0])
        self.predictions = np.array(predictions)
    def check(self, y):
        correct_predictions = np.sum(self.predictions == y)
        total_predictions = len(self.predictions)
        accuracy = correct_predictions / total_predictions
        return(f'The model had a {accuracy} accuracy score')

In [54]:
#creates an instance of neural network class
nn = NeuralNetwork(inputs=2, hiddenNodes=8)
# trains network and gets loss
nn.train(X, y, epochs=10000, learning_rate=.01)
# creates predictions
nn.predict(X)
# checks the models accuracy
nn.check(y)


Loss after 10000 epochs was 0.05125916383849586



'The model had a 0.9458 accuracy score'

This multilayer perception works better because it can adapt to the non-linearity of the data in a way that the perceptron could not. Could not get a perfect score because some kids were brave enough to try bad candy. And there isn't no feature for the model to detect this

In [55]:
for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.94741068]
 [0.94777019]
 [0.94741068]
 ...
 [0.94741068]
 [0.94741068]
 [0.94777019]]
Loss: 
 0.05125916383849586

Loss after 100 epochs was 0.49999997387083933

+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[6.0263532e-20]
 [5.5381860e-08]
 [6.0263532e-20]
 ...
 [6.0263532e-20]
 [6.0263532e-20]
 [5.5381860e-08]]
Loss: 
 0.49999997387083933

Loss after 100 epochs was 0.49999997043481964

+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[6.02917094e-20]
 [6.26646486e-08]
 [6.02917094e-20]
 ...
 [6.02917094e-20]
 [6.02917094e-20]
 [6.26646486e-08]]
Loss: 
 0.49999997043481964

Loss after 100 epochs was 0.49999

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [6]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
182   61    0   0       130   330    0        0      169      0      0.0   
246   56    0   0       134   409    0        0      150      1      1.9   
28    65    0   2       140   417    1        0      157      0      0.8   
44    39    1   2       140   321    0        0      182      0      0.0   
207   60    0   0       150   258    0        0      157      0      2.6   

     slope  ca  thal  target  
182      2   0     2       0  
246      1   2     3       0  
28       2   1     2       1  
44       2   0     2       1  
207      1   2     3       0