<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [7]:
##### Your Code Here #####
import numpy as np

X = np.array(([[0,0,1],
              [0,1,1],
              [1,0,1],
              [0,1,0],
              [1,0,0],
              [1,1,1],
              [0,0,0]]), dtype=int)
y = np.array(([[0],
              [1],
              [1],
              [1],
              [1],
              [0],
              [0]]), dtype=int)


In [9]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 1],
       [0, 0, 0]])

In [20]:
class Neural_Network(object):
    def __init__(self):
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        #initlize weights
        #Matrix Array for the First Layer
        self.L1_weights = np.random.rand(self.inputs, self.hiddenNodes) #(3x4)
        
        #Matrix Array for Hidden to Output
        self.L2_weights = np.random.rand(self.hiddenNodes, self.outputNodes) #(4x1)
        
    def feed_forward(self, X):
        #weighted sum between inputs and hidden layer
        self.hidden_sum = np.dot(X, self.L1_weights)
        #Activation of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        #self.activated_hidden = self.ReLU(self.hidden_sum)
        #weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.L2_weights)
        #final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        #self.activated_output = self.ReLU(self.output_sum)
        return self.activated_output
    
    def sigmoid(self, s):
        return 1/(1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) #applying derivative of sigmoid to error
        #self.o_delta = self.o_error*self.ReLUPrime(o)
        
        self.z2_error = self.o_delta.dot(self.L2_weights.T) #z2 error:how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden) #applying derivative of sigmoid to z2 error
        #self.z2_delta = self.z2_error*self.ReLUPrime(self.activated_hidden)
        
        self.L1_weights += X.T.dot(self.z2_delta) #adjusting first set (input --> hidden) weights
        self.L2_weights += self.activated_hidden.T.dot(self.o_delta) #adjusting second set (hidden -->output)weights
        
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
                

In [21]:
nn = Neural_Network()
nn.train(X, y)

In [22]:
# Train my 'net

nn = Neural_Network()

# Number of Epochs / Iterations
for i in range(10000): #trains the nn 10,000
    if i+1 in [1,2,3,4,5] or (i+1) % 1000 == 0:
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print("Input: \n", X)
        print("Actual Output: \n", y)
        print("Predicted Output: \n" + str(nn.feed_forward(X)))
        print("Loss: \n" + str(np.mean(np.square(y - nn.feed_forward(X))))) #mean sum squared loss
        print("\n")
    nn.train(X, y)
        

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.79645002]
 [0.83248666]
 [0.83062833]
 [0.79293564]
 [0.78960384]
 [0.85345934]
 [0.74151883]]
Loss: 
0.29378076404502196


+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.71877292]
 [0.75291035]
 [0.74927042]
 [0.71882789]
 [0.71369127]
 [0.77213372]
 [0.67454181]]
Loss: 
0.2646829594333216


+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.64235982]
 [0.67012456]
 [0.66471387]
 [0.6460794 ]
 [0.63932591]
 [0.68374083]
 [0.61222169]]
Loss: 
0.2473604632145467


+---------EPOCH 4---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [ ]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.datasets import mnist

In [1]:
# input image dimensions
img_rows, img_cols = 28, 28

In [2]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

NameError: name 'mnist' is not defined

In [32]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [16]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [33]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [40]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [ ]:
##### Your Code Here #####



## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?